apiVersion: apps/v1
kind: Deployment
metadata:
    name: devops
    namespace: default
    labels:
        app: devops
spec:
    replicas: 1
    selector:
        matchLabels:
            app: devops
    template:
        metadata:
            labels:
                app: devops
        spec:
            containers:
                - name: devops
                  image: emirfurkan/flask-devops:latest
                  ports:
                      - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
    name: devops
    namespace: default
spec:
    selector:
        app: devops
    ports:
        - protocol: TCP
          port: 80
          targetPort: 5000
    type: LoadBalancer
